### ISSUE TITLE
Collecting Body Weight from user

### ISSUE THREAD

**Issue by fdagreat** [kitindi/myClinicCard#3]
I think we need to keep a a section on the dashboard where the user can input their Body weight, and the data will be rendered in the My Health Trends Graphs. 

We can start by adding the Ui in the Figma design 
@kitindi

**Comment by kitindi** [comment]
Yes, that is a good idea, initially, I was thinking to add that feature in the clinic report page where user will add the feedback she got from the clinic visit on that particular month including doctor's recommendations, current body weight, blood level, pregnant status( good condition/need monitoring) as well as the vaccination taken. I have a feeling that there will be too many CTAs on the dashboard window.

**Comment by fdagreat** [comment]
True it should not be on the Dashboard, cool let's keep it in the Clinic Report Page. 👍

**Comment by fdagreat** [comment]
@kitindi Added it on the feature Report Card page
