### ISSUE TITLE
Add A Notification Panel

### ISSUE THREAD

**Issue by fdagreat** [kitindi/myClinicCard#4]
This could be below the User profile component on the Dashboard 

- [x] Design Notification Panel
- [ ] Create Notification Component

and we can use it to show notifications to the user, such as;

- [ ]  Reminder to Input Body Weight if due day is close or passed 

- [ ]  Reminder for notifications which are not closed by deadline passed 

- [ ]  Daily Health Tips 

- [ ]  Daily messages of articles which can be helpful for the user to read

i guess each of the items can be a separate issue and we can create the new issues after completing one and close this when done with all. @kitindi

**Comment by kitindi** [comment]
I like these ideas, notification is an awesome feature, I didn't want to make the project complicated initially now since we are two, I am hopeful that we can take this very far.
@fdagreat

**Comment by kitindi** [comment]
- 

- [ ]
